secrets_filepath = ".env"
[mqtt.broker]
hostname = "gfyvrdatadash"
port = 1_883

[mqtt.node_network]
topic_structure = "machine/module/measurement/field*"
enable_prometheus_server = false
prometheus_port = 8_000
