secrets_filepath = ".env"

[mqtt.broker]
hostname = "pi-monitor.local"
port = 1_883

[mqtt.node_network]
node_id = "node-client-0"
publish_period = 5
subscribe_topics = [
  "+/metric",
]
enable_prometheus_server = true
prometheus_port = 8_001

[influxdb]
config_filepath = "config/.influxdb.toml"