secrets_filepath = ".env"

[mqtt.broker]
hostname = "localhost"
port = 1_883

[mqtt.node_network]
enable_prometheus_server = false
prometheus_port = 8_000

[mqtt.subscriber]
node_id = "node-subscriber-0"
subscribe_topics = [
  "#",
]

[mqtt.publisher]
node_id = "node-publisher-0"
publish_period = 10