secrets_filepath = ".env"

[mqtt.broker]
hostname = "emqx-broker"
port = 1_883

[mqtt.node_network]
topic_structure = "module/measurement/field*"
enable_prometheus_server = false
prometheus_port = 8_000

[mqtt.client]
node_id = "mqtt_client_0"
subscribe_topics = ["topic_0/#"]
subscribe_qos = 0
