secrets_filepath = ".env"

[mqtt.broker]
hostname = "gfyvrdatadash"
port = 1_883

[mqtt.node_network]
topic_structure = "machine/level/datatype/module/measurement/field*"
enable_prometheus_server = false
prometheus_port = 8_000

[mqtt.client]
node_id = "metrics_manager_pzero"
subscribe_topics = ["prototype-zero/#"]
subscribe_qos = 0
