secrets_filepath = ".env"

[mqtt.broker]
hostname = "gfyvrdatadash"
port = 1_893

[mqtt.node_network]
enable_prometheus_server = true
topic_structure = "module/measurement/field*"
prometheus_port = 8_000

[mqtt.client]
node_id = "mqtt_client_1"
subscribe_topics = ["topic_0/#"]
subscribe_qos = 1

[mqtt.client.metrics.latency]
enabled = true
interval = 1
qos = 1
