version: 1

handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : INFO
    stream  : ext://sys.stdout
  mqtt_node_network.debug.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/mqtt_node_network.debug.log
    maxBytes: 1_000_000
    backupCount: 3
  mqtt_node_network.info.file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : INFO
    filename: logs/mqtt_node_network.info.log
    maxBytes: 1_000_000
    backupCount: 3

formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  verbose:
    format: "%(asctime)s,%(msecs)d - %(name)s - %(levelname)-8s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(message)s'

loggers:
  root:
    level: DEBUG
    handlers:
      - console
      - mqtt_node_network.debug.file
      - mqtt_node_network.info.file
